name: manage-azure-policy-927bb421
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'RkInitiative/initiatives/Tagging_Governance_v2.0_f4a18e6d18fa4fc0ae09d437/**'
#      - .github/workflows/manage-azure-policy-927bb421.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_927bb421}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          RkInitiative/initiatives/Tagging_Governance_v2.0_f4a18e6d18fa4fc0ae09d437/**
